# Generated by Django 4.1.3 on 2022-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField()),
                ('intubed', models.IntegerField()),
                ('pneumonia', models.IntegerField()),
                ('age', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('copd', models.IntegerField()),
                ('asthma', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('cardiovascular', models.IntegerField()),
                ('obesity', models.IntegerField()),
                ('renal_chronic', models.IntegerField()),
                ('tobacco', models.IntegerField()),
                ('contact_other_covid', models.IntegerField()),
                ('icu', models.IntegerField()),
                ('classification', models.IntegerField()),
            ],
        ),
    ]
